apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - name: flask-app1
        image: sakshigmoschip/flask-app1
        ports:
        - containerPort: 5000